#!/bin/bash
# Sets up the Cobalt tvOS simulator cross build on Linux:
# unpacks artifacts, installs darwin compiler-rt, applies source patches,
# writes args.gn, and runs gn gen.
#
# Cobalt variant of setup_linux.sh (see RUNBOOK.md). Differences:
#  - patch file is tvos-cross-cobalt.patch (rebased for Cobalt's older
#    Chromium base; the user_data_importer hunk does not exist there).
#  - args.gn imports Cobalt's platform config
#    (cobalt/build/configs/tvos-arm64-simulator/args.gn) and mirrors what
#    cobalt/build/gn.py writes (build_type, reclient cfg dir, use_siso=false),
#    so the build uses Cobalt's reclient RBE setup instead of siso.
#
# Prerequisites:
#  - artifacts from make_artifacts_mac.sh in $ARTIFACTS_DIR
#  - reclient auth working (same as regular Cobalt linux RBE builds)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_ROOT="${SRC_ROOT:-$HOME/projects/cobalt/src}"
ARTIFACTS_DIR="${ARTIFACTS_DIR:-$HOME/mac-toolchain}"
BUILD_DIR="${BUILD_DIR:-out/tvos-sim}"
BUILD_TYPE="${BUILD_TYPE:-devel}"
USE_REMOTEEXEC="${USE_REMOTEEXEC:-true}"
TOOLCHAIN_REL="third_party/tvos_toolchain_local"
TOOLCHAIN_DIR="$SRC_ROOT/$TOOLCHAIN_REL/chromium-tvos-toolchain"

cd "$SRC_ROOT"

# 0) Sanity checks -----------------------------------------------------------
[ -f "$ARTIFACTS_DIR/chromium-tvos-toolchain.zip" ] || {
  echo "ERROR: $ARTIFACTS_DIR/chromium-tvos-toolchain.zip not found"; exit 1; }
[ -f "$ARTIFACTS_DIR/chromium-mac-extra.zip" ] || {
  echo "ERROR: $ARTIFACTS_DIR/chromium-mac-extra.zip not found"; exit 1; }

# 1) Unpack artifacts --------------------------------------------------------
mkdir -p "$TOOLCHAIN_REL"
unzip -oq "$ARTIFACTS_DIR/chromium-tvos-toolchain.zip" -d "$TOOLCHAIN_REL"
mkdir -p "$TOOLCHAIN_REL/mac_extra"
unzip -oq "$ARTIFACTS_DIR/chromium-mac-extra.zip" -d "$TOOLCHAIN_REL/mac_extra"
# The linker requires this -L directory to exist even when no Swift is linked.
mkdir -p "$TOOLCHAIN_DIR/usr/lib/swift/iphonesimulator"

# 2) Install darwin compiler-rt into cobalt's clang ---------------------------
# NOTE: rerun this step after every clang roll / gclient sync (it is wiped).
CLANG_VER_DIR="$(ls -d third_party/llvm-build/Release+Asserts/lib/clang/*/ | head -n1)"
mkdir -p "${CLANG_VER_DIR}lib/darwin"
rsync -a "$TOOLCHAIN_REL/mac_extra/chromium-mac-extra/clang-rt-darwin/" "${CLANG_VER_DIR}lib/darwin/"
echo "compiler-rt installed into ${CLANG_VER_DIR}lib/darwin"

# 3) Apply source patches (idempotent) ----------------------------------------
PATCH="$SCRIPT_DIR/tvos-cross-cobalt.patch"
if git apply --check --reverse "$PATCH" 2>/dev/null; then
  echo "patches already applied"
elif git apply --check "$PATCH" 2>/dev/null; then
  git apply "$PATCH"
  echo "patches applied"
else
  echo "ERROR: $PATCH does not apply cleanly; rebase it against your tree"; exit 1
fi

# 4) Write args.gn from sdk_info.txt ------------------------------------------
INFO="$TOOLCHAIN_DIR/sdk_info.txt"
val() { awk -F': ' -v k="$1" '$1==k{print $2}' "$INFO"; }
XCODE_VERBATIM="$(val xcode_version_verbatim)"   # e.g. 26.6
XCODE_BUILD="$(val xcode_build)"                 # e.g. 17F113
SDK_VERSION="$(val sdk_version)"                 # e.g. 26.5
SDK_BUILD="$(val sdk_build)"                     # e.g. 23L470
MACHINE_BUILD="$(val machine_os_build)"          # e.g. 25F84
# Fallback for bundles created by the first-generation mac script whose
# sdk_info.txt had: "xcodebuild: Xcode 26.6 Build version 17F113"
if [ -z "$XCODE_VERBATIM" ]; then
  XCODE_VERBATIM="$(awk '/^xcodebuild:/{print $3}' "$INFO")"
  XCODE_BUILD="$(awk '/^xcodebuild:/{print $NF}' "$INFO")"
fi
for v in XCODE_VERBATIM XCODE_BUILD SDK_VERSION SDK_BUILD MACHINE_BUILD; do
  [ -n "${!v}" ] || { echo "ERROR: could not parse $v from $INFO"; exit 1; }
done
# FormatVersion: "26.6" -> 2660, "8.2.1" -> 0821 (same as sdk_info.py)
XCODE_INT="$(python3 -c "
import sys,itertools
v='$XCODE_VERBATIM'.split('.')
maj,mi,pa=list(itertools.islice(itertools.chain(v,itertools.repeat('0')),0,3))
print(('%2s%s%s'%(maj,mi,pa)).replace(' ','0'))")"

mkdir -p "$BUILD_DIR"
cat > "$BUILD_DIR/args.gn" <<EOF
# Cobalt tvOS simulator cross build on Linux.
# Generated by setup_cobalt_linux.sh from $TOOLCHAIN_REL sdk_info.txt.

# What cobalt/build/gn.py would write for -p tvos-arm64-simulator -c $BUILD_TYPE.
use_siso = false
use_remoteexec = $USE_REMOTEEXEC
rbe_cfg_dir = rebase_path("//cobalt/reclient_cfgs")
build_type = "$BUILD_TYPE"
symbol_level = 1
is_debug = false
import("//cobalt/build/configs/tvos-arm64-simulator/args.gn")

# Cross-compile: SDK provided externally (skips sdk_info.py / xcodebuild).
use_system_xcode = false
ios_sdk_path = "//$TOOLCHAIN_REL/chromium-tvos-toolchain/AppleTVSimulator.sdk"
ios_sdk_platform_path = "//$TOOLCHAIN_REL/chromium-tvos-toolchain/AppleTVSimulator.platform"
ios_toolchains_path = "//$TOOLCHAIN_REL/chromium-tvos-toolchain"
ios_bin_path = "//$TOOLCHAIN_REL/chromium-tvos-toolchain/"
ios_sdk_name = "appletvsimulator"
ios_sdk_platform = "AppleTVSimulator"

ios_sdk_version = "$SDK_VERSION"
ios_sdk_build = "$SDK_BUILD"
xcode_version = "$XCODE_INT"
xcode_version_int = $XCODE_INT
xcode_build = "$XCODE_BUILD"
machine_os_build = "$MACHINE_BUILD"

# Simulator builds are not signed; avoid mac-only tooling.
ios_enable_code_signing = false
enable_dsyms = false

# Point the mac-sdk plumbing (imported via gn_logs.gni even for iOS targets)
# at the flattened tvOS bundle which carries version.plist at its root.
mac_hermetic_xcode_path = "//$TOOLCHAIN_REL/chromium-tvos-toolchain"
mac_hermetic_xcode_flat_layout = true
EOF

# 5) gn gen -------------------------------------------------------------------
buildtools/linux64/gn gen "$BUILD_DIR" --check
echo
echo "Ready. Build with e.g.:"
echo "  autoninja -C $BUILD_DIR base"
